---
abstract: 'run nginx proxy server'
author:
  - ', Sergey Zasenko.'
build_requires:
  ExtUtils::MakeMaker: 6.62
  IO::Socket::INET: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Test::Spec: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nginx-Runner
no_index:
  directory:
    - inc
    - t
requires:
  File::Temp: 0
  IPC::Open3: 0
  perl: 5.8.1
resources:
  bugtracker: https://github.com/und3f/nginx-runner/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/und3f/nginx-runner
version: 0.000001_1
